// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using deliverAPI.Data;

namespace deliverAPI.Migrations
{
    [DbContext(typeof(contasDbContext))]
    [Migration("20201008100146_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("deliverAPI.Models.clContas", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DiasAtraso")
                        .HasColumnType("int");

                    b.Property<string>("DtPagto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DtVenc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegraCalculo")
                        .HasColumnType("int");

                    b.Property<double>("ValOrig")
                        .HasColumnType("float");

                    b.HasKey("Nome");

                    b.ToTable("clContas");
                });
#pragma warning restore 612, 618
        }
    }
}
